### ISSUE TITLE
专门做个Tampermonkey的版本(￣▽￣)"

### ISSUE THREAD

**Issue by Yukipedia** [seerainfog/bilibili-coin#1]
# 专门做个Tampermonkey的版本(￣▽￣)"
看说明这个项目是边学Vue边做的
不过再做个Tampermonkey的脚本比较方便
比如在看某个用户空间的时候激活脚本，自动获取硬币数量并显示
以及有个小按钮在B站某个页面显眼的地方点击后有搜索框感觉挺不错的

🎉

**Comment by seerainfog** [comment]
嗯~ 我会尝试着去做做看的。 (=′∇`=）
